name: thesis
description: "Student card verification application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0-234.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.4.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  gap: ^3.0.1
  another_flushbar: 1.12.30
  vibration: 3.1.3
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  dio_http: ^5.0.4
  image_picker: ^1.0.4
  camera: ^0.10.6
  mobile_scanner: ^5.2.3
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  google_mlkit_face_detection: ^0.11.0
  image: ^3.3.0
  vector_math: ^2.1.4
  equatable: ^2.0.0
  tflite_flutter: ^0.12.1
#  tflite_flutter_helper: ^0.2.2
#dependency_overrides:
#  tflite_flutter: ^0.12.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.9
  flutter_gen_runner: 5.3.2



flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/svg/
    - assets/lottie/
    - assets/font/open_sans/
    - assets/model/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/font/open_sans/OpenSans-Light.ttf
          style: normal
          weight: 300
        - asset: assets/font/open_sans/OpenSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/font/open_sans/OpenSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/font/open_sans/OpenSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/font/open_sans/OpenSans-Bold.ttf
          style: normal
          weight: 700

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

  assets:
    outputs:
      enabled: true
      style: dot-delimiter
      package_parameter_enabled: false

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
